# Generated by Django 4.0.6 on 2022-07-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
                ('potencia', models.IntegerField()),
                ('año', models.IntegerField()),
                ('placa', models.CharField(max_length=50)),
            ],
        ),
    ]
